name: Linter
on: pull_request
jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - name: Install ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"
      - run: ruff check --no-cache
  ruff-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - name: Install ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"
      - run: ruff format --check --diff --no-cache